version: "3"
services:
  auth:
    image: carlosvj/fablat:fablat-auth
    ports:
      - "9999:9999"
    environment:
      VIRTUAL_HOST: fablat.net
      LETSENCRYPT_HOST: fablat.net
  resource:
    image: carlosvj/fablat:fablat-resource
    ports:
      - "9000:9000"
    environment:
      VIRTUAL_HOST: fablat.net
      LETSENCRYPT_HOST: fablat.net
    links:
      - auth
  ui:
    image: carlosvj/fablat:fablat-ui
    links:
      - auth
      - resource
    environment:
      VIRTUAL_HOST: fablat.net
      LETSENCRYPT_HOST: fablat.net
      LETSENCRYPT_EMAIL: cvj_2311@hotmail.com
    expose:
      - "80"
      - "443"
networks:
  default:
    external:
      name: nginx-proxy