version: "3"
services:
  auth:
    image: carlosvj/fablat:fablat-auth
    ports:
      - "9999:9999"
    links:
      - ui
  resource:
    image: carlosvj/fablat:fablat-resource
    ports:
      - "9000:9000"
    links:
      - auth   
  ui:
    image: carlosvj/fablat:fablat-ui
    ports:
      - "80:8080"
    links:
      - auth
      - resource