auth:
  build: ./fablat.auth
  ports:
    - "9999:9999"
    
resource:
  build: ./fablat.resource
  ports:
    - "9000:9000"
  links:
    - auth

ui:
  build: ./fablat.ui
  ports:
    - "8080:8080"
  links:
    - auth
    - resource