server:
  port: 80
  
debug: true

spring:
  aop:
    proxy-target-class: true
security:
  oauth2:
    client:
      accessTokenUri: http://auth.fablat.net/uaa/oauth/token
      userAuthorizationUri: http://auth.fablat.net/uaa/oauth/authorize
      clientId: fablat
      clientSecret: c6d4f0e6125fcc1879b8dc42983c73ea1b1adf4f67a1cba0010d29ed8895017c
      scope: openid
    resource:
      userInfoUri: http://auth.fablat.net/uaa/user

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://resource
    user:
      path: /user/**
      url: http://auth/uaa/user
  
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG